### 회원가입
POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"min@codeit.kr",
  "name":"minholee",
  "password":"password"
}

### 토큰 기반 로그인
POST http://localhost:3000/login
Content-Type: application/json

{
  "email":"min@codeit.kr",
  "password":"password"
}

### 엑세스토큰재발급, 리프레쉬토큰재발급
POST http://localhost:3000/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTc0MjM3Njc4NywiZXhwIjoxNzQzNTg2Mzg3fQ.46Y0YWghfWAvSyVkPt1P7omkSLktw-KqObimO0LBt8w

### 세션 기반 로그인
POST http://localhost:3000/session-login
Content-Type: application/json

{
  "email":"min@codeit.kr",
  "password":"password"
}

### 세션 로그아웃
POST http://localhost:3000/session-logout
Cookie: connect.sid=s%3AIjUx4Qr4pLRGZQ3ujPBWNh3BM7TWIneG.30c1fKiXPLZks2uxbARFBbw5Mxfaur6y1K3AyppbTrA